"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AppShell, EmptyState, LoadingState } from "@/app/components/AppShell";

type Item = { id: string; name: string; code?: string; regionId?: string; constituencyId?: string; electoralAreaId?: string };
type Data = { regions: Item[]; constituencies: Item[]; electoralAreas: Item[]; pollingStations: Item[] };

export default function LocationsPage() {
  const [data, setData] = useState<Data | null>(null); const [type, setType] = useState("region"); const [notice, setNotice] = useState("");
  const load = useCallback(() => fetch("/api/locations").then(async (r) => { const value = await r.json(); if (!r.ok) throw new Error(value.error ?? "Could not load locations."); setData({ regions: value.regions ?? [], constituencies: value.constituencies ?? [], electoralAreas: value.electoralAreas ?? [], pollingStations: value.pollingStations ?? [] }); }).catch((error) => setNotice(error instanceof Error ? error.message : "Could not load locations.")), []); useEffect(() => { load(); }, [load]);
  const parents = useMemo(() => { if (!data) return []; if (type === "constituency") return data.regions; if (type === "electoral_area") return data.constituencies; if (type === "polling_station") return data.electoralAreas; return []; }, [data, type]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const body = Object.fromEntries(new FormData(form)); const response = await fetch("/api/locations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) return setNotice(result.error ?? "Could not add location."); setNotice("Location added."); form.reset(); setType("region"); await load(); }
  return <AppShell eyebrow="GEOGRAPHY" title="Locations"><div className="page-content"><div className="location-layout"><form className="settings-card" onSubmit={submit}><div className="card-title"><div><small>NEW LOCATION</small><h2>Build your hierarchy</h2><p>Add records from region down to polling station.</p></div></div>{notice && <div className="alert">{notice}</div>}<div className="form-grid"><label className="wide"><span>Location type</span><select name="type" value={type} onChange={(e) => setType(e.target.value)}><option value="region">Region</option><option value="constituency">Constituency</option><option value="electoral_area">Electoral area</option><option value="polling_station">Polling station</option></select></label>{parents.length > 0 && <label className="wide"><span>Parent location</span><select name="parentId" required><option value="">Choose parent</option>{parents.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<label><span>Name</span><input name="name" required /></label><label><span>Code</span><input name="code" required={type !== "electoral_area"} /></label>{type === "polling_station" && <label className="wide"><span>Address</span><input name="address" /></label>}</div><button className="primary-button" type="submit">Add location</button></form><section className="data-card"><div className="card-title"><div><small>HIERARCHY</small><h2>Location records</h2></div></div>{!data ? <LoadingState /> : data.regions.length === 0 ? <EmptyState title="No locations yet" body="Start by adding a region, then work down the hierarchy." /> : <div className="location-list">{data.regions.map((region) => <div key={region.id}><strong>{region.name}</strong><small>{data.constituencies.filter((x) => x.regionId === region.id).length} constituencies</small></div>)}</div>}</section></div></div></AppShell>;
}
